body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a Qlty feature.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem could Qlty solve that it doesn't?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution brainstorm (optional)
      description: We'd love to hear your ideas for how we can solve this problem.

  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [contribution process](https://github.com/qltysh/codeclimate/blob/main/CONTRIBUTING.md#triage-process) for what to expect next.
