body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question about Qlty. We are happy to help! 🙏 Please follow the sections in the template and provide as much information as possible about your problem.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Provide a clear and concise description of the question you have or problem you want to discuss.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce (optional)
      description: If your question is about specific behaviour of Qlty, tell us how to reproduce it.
      value: |
        <!--
        1. Go to '...'
        2. Change '....'
        3. Run '....'
        4. See error
        -->

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior (optional)
      description: A clear and concise description of what you expected to happen.

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: What version of the CLI are you running?
      placeholder: qlty --version
    validations:
      required: true

  - type: textarea
    id: qlty-info
    attributes:
      label: Information about Qlty configuration and environment (optional)
      value: |
        <!-- Paste your Qlty project config below -->
        ```toml
        // Add your qlty.toml
        ```

        - OS: <!--[e.g. macOS, Windows, Debian, CentOS, ...]-->
