name: Bug report
description: File a bug report.
title: "Bug: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: actual-behavior
    attributes:
      label: What happened?
      description: The more details, the better.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: reproducible
    attributes:
      label: Can you reproduce the problem?
      options:
        - Yes, consistently
        - Only sometimes
        - "No"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: What version of the CLI are you running?
      placeholder: qlty --version
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [contribution process](https://github.com/qltysh/codeclimate/blob/main/CONTRIBUTING.md#triage-process) for what to expect next.
