name: Plugin request
description: Request a new linter or auto-formatter plugin.
title: "Plugin request: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a plugin!

  - type: input
    id: name
    attributes:
      label: What is the name of the static analysis tool?
    validations:
      required: true

  - type: input
    id: docs-url
    attributes:
      label: Where is the tool's documentation published?
      description: Please provide a URL to the documentation.
    validations:
      required: true

  - type: input
    id: releases-url
    attributes:
      label: Where are releases published?
      description: Please provide a URL to the releases page.
    validations:
      required: true

  - type: input
    id: languages
    attributes:
      label: What programming languages or other file types does the tool support?
      description: Please list the languages or file types.
    validations:
      required: true

  - type: dropdown
    id: tool-type
    attributes:
      label: What type of tool is this?
      multiple: true
      options:
        - Linter
        - Auto-formatter
        - Type checker
        - Security scanner
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the plugin request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
