blank_issues_enabled: false
contact_links:
  - name: Qlty Community Support
    url: https://github.com/orgs/qltysh/discussions
    about: Please ask and answer questions here.
  - name: Qlty Security Contact
    url: mailto:security@qlty.sh
    about: Please report security vulnerabilities here.
